Inhomogeneous
JuliaEarth/PointPatterns.jl pull request #32
Opened 2023-06-05 19:17 UTC by ErickChacon

This is still WIP, but this PR tackles JuliaEarth/GeoStats.jl#264. No need to check but suggestions are welcome.  So far:

- Old method for `ProductSampling` is being removed because we already handle that type of sampling in `Meshes.jl`, so that will be called indirectly when using `sample(g, HomogeneousSampling(n))`.
- `ThinnedSampling` is implemented assuming the user provide the `lambdamax`, this is common in other languages.

Things to add:

- Compute `lambdamax` when not provided.
- Add `PossionProcess` for intensity as CartesianGrid or a Mesh.

2023-06-05 19:30 UTC, juliohm commented
Thank you @ErickChacon , that is great. I released a new version of Meshes.jl so that we can add the compat entry here for the Box method. If the ProductSampling struct is not used anywhere else, we can remove it completely from here. Also any dependency that is imported to implement the ProductSampling method could be dropped.

2023-06-06 01:39 UTC, ErickChacon commented
@juliohm, I think we also do not need `DiscretizedSampling`.  For example, the following code is not necessary to implement:

https://github.com/JuliaEarth/PointPatterns.jl/blob/ade3c2b682efc34300bdd48a27520b8e2e280f0c/src/processes/poisson.jl#L65-L74

Because `Meshes.jl` is already handling that. Our function can already handle a `Geometry` and `Mesh` thanks to the sampling algorithms in `Meshes.jl`.

2023-06-06 05:00 UTC, ErickChacon commented
For the case that where the intensity is piecewise constant over a mesh, it  would be nice to define something like:

```julia
struct PoissonProcess{L<:Vector} <: PointProcess
  λ::L
  m::Mesh
end
```

But seems it is not possible. Another option would be to define the PoissonProcess with the associated geometry allways, but this might be a bit limiting (although it is very common in other languages).

2023-06-06 11:42 UTC, juliohm requested changes

2023-06-06 11:42 UTC, juliohm commented on src/processes.jl
> +Base.rand(rng::Random.AbstractRNG, p::PointProcess, g::GeometryOrMesh, n::Int; algo=default_sampling_algorithm(p, g)) =
Let's omit the type annotation in this case and leave `g` without type. That way we avoid introducing the union type and everything should work fine in the Meshes.jl side with proper types.

```suggestion
Base.rand(rng::Random.AbstractRNG, p::PointProcess, g, n::Int; algo=default_sampling_algorithm(p, g)) =
```

2023-06-06 11:42 UTC, juliohm commented on src/processes.jl
> +Base.rand(rng::Random.AbstractRNG, p::PointProcess, g::GeometryOrMesh; algo=default_sampling_algorithm(p, g)) =
```suggestion
Base.rand(rng::Random.AbstractRNG, p::PointProcess, g; algo=default_sampling_algorithm(p, g)) =
```

2023-06-06 11:42 UTC, juliohm commented on src/processes.jl
> +Base.rand(p::PointProcess, g::GeometryOrMesh, n::Int; algo=default_sampling_algorithm(p, g)) =
```suggestion
Base.rand(p::PointProcess, g, n::Int; algo=default_sampling_algorithm(p, g)) =
```

2023-06-06 11:42 UTC, juliohm commented on src/processes.jl
> +Base.rand(p::PointProcess, g::GeometryOrMesh; algo=default_sampling_algorithm(p, g)) =
```suggestion
Base.rand(p::PointProcess, g; algo=default_sampling_algorithm(p, g)) =
```

2023-06-06 11:42 UTC, juliohm commented on src/processes/binomial.jl
> +default_sampling_algorithm(::BinomialProcess, ::GeometryOrMesh) = DiscretizedSampling()
```suggestion
default_sampling_algorithm(::BinomialProcess, ::Any) = DiscretizedSampling()
```

2023-06-06 11:42 UTC, juliohm commented on src/processes/poisson.jl
> +function rand_single(rng::Random.AbstractRNG, p::PoissonProcess{<:Real}, g::GeometryOrMesh, ::DiscretizedSampling)
```suggestion
function rand_single(rng::Random.AbstractRNG, p::PoissonProcess{<:Real}, g, ::DiscretizedSampling)
```

2023-06-06 11:42 UTC, juliohm commented on src/processes/poisson.jl
> +function rand_single(rng::Random.AbstractRNG, p::PoissonProcess{<:Function}, g::GeometryOrMesh, algo::ThinnedSampling)
```suggestion
function rand_single(rng::Random.AbstractRNG, p::PoissonProcess{<:Function}, g, algo::ThinnedSampling)
```

2023-06-06 11:42 UTC, juliohm commented on src/PointPatterns.jl
> +
```suggestion
```

2023-06-06 11:42 UTC, juliohm commented on src/processes.jl
> +  λmax::Real
```suggestion
struct ThinnedSampling{T<:Real}
  λmax::T
```

2023-06-06 18:42 UTC, ErickChacon commented
@juliohm Do you have a recommended way to represent an empty `PointSet` (or just use `empty`)?  We might need it to when no points are sampled (when the intensity is very low).

2023-06-06 18:50 UTC, juliohm commented
> @juliohm Do you have a recommended way to represent an empty `PointSet`? We might need it to when no points are sampled (when the intensity is very low).

We don't have that implemented yet. I thought about it a few times in some algorithms but never ended up needing it. Maybe we should enforce in the algorithm itself that empty sets of points will never occur? Because if someone wants to sample from the random process, he/she expects at least one sample, right?

2023-06-06 19:00 UTC, ErickChacon commented
> We don't have that implemented yet. I thought about it a few times in some algorithms but never ended up needing it. Maybe we should enforce in the algorithm itself that empty sets of points will never occur? Because if someone wants to sample from the random process, he/she expects at least one sample, right?

I think is understandable that the number of points of the realization of the process might be (in very few cases) 0. If we modify the algorithm to ensure no empty pointsets, then we introduce some bias when studying the properties of the process using simulations.

2023-06-06 19:24 UTC, juliohm commented
Do you think we can easily adjust our current PointSet to handle the empty case? I am just scared of these empty case scenarios when it comes to type stability, but feel free to submit a PR to Meshes.jl and we can review the implications of considering empty domains.

2023-06-06 19:56 UTC, ErickChacon commented
> Do you think we can easily adjust our current PointSet to handle the empty case? I am just scared of these empty case scenarios when it comes to type stability, but feel free to submit a PR to Meshes.jl and we can review the implications of considering empty domains.

I will try to add that here and later move to Meshes.jl.

2023-06-06 23:16 UTC, juliohm commented on src/processes/poisson.jl
> +default_sampling_algorithm(::PoissonProcess{<:Function}, ::Any) = ThinnedSampling()
It seems that our default sampling algorithm is no longer a function of the geometry. Maybe we should simply erase the second argument?

2023-06-07 04:55 UTC, ErickChacon commented
@juliohm I think this is completed. Please review the current version.

2023-06-07 11:02 UTC, juliohm requested changes
Excited to see the inhomogeneous case finally showing up 💯 !

Attached a first round of reviews.

2023-06-07 11:02 UTC, juliohm commented on src/processes/poisson.jl
> +end
I understand that this is a procedure to find a good lambda_max for a grid. I would simply introduce a new function to get this default_lambda_max and would use it elsewhere. Right now we are artificially introducing a new method of rand_single just to compute the lambda_max.

Also, maybe we can remove the redundancy between ThinnedSampling and SimpleThinnedSampling with a type parameter? It is not clear to me yet why we need two separate structs.

2023-06-07 11:02 UTC, juliohm commented on src/processes/poisson.jl
> +function rand_single(rng::Random.AbstractRNG, p::PoissonProcess{<:Function}, m::Mesh, algo::DiscretizedSampling)
```suggestion
function rand_single(rng::Random.AbstractRNG, p::PoissonProcess{<:Function}, d::Domain, algo::DiscretizedSampling)
```

2023-06-07 11:02 UTC, juliohm commented on src/processes/poisson.jl
> +  c = centroid.(m)
```suggestion
  c = centroid.(d)
```

2023-06-07 11:02 UTC, juliohm commented on src/processes/poisson.jl
> +  rand_single(rng, PoissonProcess(λvec), m, algo)
```suggestion
  rand_single(rng, PoissonProcess(λvec), d, algo)
```

2023-06-07 16:52 UTC, ErickChacon commented
@juliohm I removed the method `SimpleThinnedSampling`. I pushed to my fork, but I do not know why I can't see the changes in the PR.

2023-06-07 20:29 UTC, juliohm commented on src/PointPatterns.jl
> +  ThinnedSampling
```suggestion
  thin
```
I think these sampling algorithms are internal implementation details right? Not intended for end-users.

2023-06-07 20:31 UTC, juliohm commented on src/processes.jl
> +end
This design isn't ideal. I think we can compute the lambda_max or any parameter inside of the method definition and leave the ThinnedSampling algorithm as an empty struct.

2023-06-07 20:32 UTC, juliohm commented on src/processes.jl
> +"""
Also, this docstring could be converted into a comment right before the method that implements the Lewis-Shedler algorithm.

2023-06-07 20:34 UTC, juliohm commented on src/processes/poisson.jl
> +default_lambda_max(p, g, algo::ThinnedSampling{T}) where {T<:Real} = algo.param
Maybe this lambda_max is not a function of the algorithm, but some internal implementation detail that we can always give a good default depending on the domain? It feels strange to request a lambda_max from end-users. After all, all they need is to simulate a Poisson process with varying intensity lambda.

2023-06-07 20:36 UTC, juliohm commented on src/processes/poisson.jl
> +end
Based on this implementation it seems that the lambda_max that is being computed is only a function of the Poisson process intensity lambda and the geometry/domain. We don't need to store lambda_max in a separate algo struct, at least it doesn't seem necessary.

2023-06-07 20:37 UTC, juliohm commented on src/processes/poisson.jl
> +function rand_single(rng::Random.AbstractRNG, p::PoissonProcess{<:Vector}, d::Domain, algo::DiscretizedSampling)
```suggestion
function rand_single(rng::Random.AbstractRNG, p::PoissonProcess{<:AbstractVector}, d::Domain, algo::DiscretizedSampling)
```

2023-06-07 20:40 UTC, juliohm commented on src/processes/poisson.jl
> +    PointSet(points)
This implementation is exactly equal to the Meshes.jl implementation for general Domain:

https://github.com/JuliaGeometry/Meshes.jl/blob/5f64dea3cf27cd555fec90d9eda6498bb6cc1c69/src/sampling/homogeneous.jl#L15-L26

If we could use that implementation instead, that would be ideal. Maybe we could simply scale the geometries in a given Domain according to the lambda vector and call the Meshes.jl method? Something along these lines would reuse the code we have there and would also be more intuitive to read.

2023-06-07 20:41 UTC, juliohm requested changes
Thank you @ErickChacon for pushing it forward. Attached a second round of reviews.

2023-06-07 20:45 UTC, juliohm commented on src/processes/poisson.jl
> +    PointSet(points)
Maybe we could use the Stretch transform on each geometry of the mesh in a lazy fashion, i.e. stretching boxes should be zero effort. We may need to add specializations in our Stretch implementation for specific geometries though: https://github.com/JuliaGeometry/Meshes.jl/blob/5f64dea3cf27cd555fec90d9eda6498bb6cc1c69/src/transforms/stretch.jl#L5-L26

2023-06-07 22:31 UTC, ErickChacon commented
@juliohm, thank you so much for reviewing this. I will continue with this PR over the weekend.

2023-06-19 05:02 UTC, ErickChacon commented
@juliohm I have simplified the`ThinnedSampling` method, and a more advanced user can use also defined `lambdamax` calling `PointPatterns.ThinnedSampling`. I like this approach because advanced users can use any other `Optimization` package for more complex intensity functions. There are still two things to consider:

1. The `DiscretizedSampling` algorithm similar to `Meshes.jl` For which I think it is easy to define a function in `Meshes.jl` for `WeightedSampling` where the weights can be provided. The internal function can be used in `Meshes.jl` and `PointPatterns.jl`.
2. The output for `ThinnedSampling` is a view. I think this is not ideal because the discarded points are not of interest at all, so there is not need to preserve those values. I think we should return a `PointSet` as in the Homogeneous case.

2023-06-19 11:43 UTC, juliohm approved these changes
Thank you @ErickChacon for pushing this forward. I agree with you that some things need to be improved like the return type of the different sampling methods and the reuse of the code in Meshes.jl.

I will proceed and merge this PR as is so that we at least have the inhomogeneous case working. We can then work on new PRs to improve the status quo. Perhaps we need to go back to Meshes.jl first to add the weights option as you suggested in the sampler over there, and come back here to reuse it instead of rewriting the code.

Appreciate all the effort to improving the point pattern analysis module, it will be really useful to the community 💯

2023-06-19 11:43 UTC, merged